controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


niryo_one_controller:
  ros__parameters:
    type: niryo_one_hardware/NiryoOneController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - tool

    command_interfaces:
      joint_1:
        - position
        - velocity
        - torque
        - mirco_steps
        - max_effort
      joint_2:
        - position
        - velocity
        - torque
        - mirco_steps
        - max_effort
      joint_3:
        - position
        - velocity
        - torque
        - mirco_steps
        - max_effort
      joint_4:
        - position
        - velocity
        - torque
        - led
      joint_5:
        - position
        - velocity
        - torque
        - led
      joint_6:
        - position
        - velocity
        - torque
        - led
      tool:
        - position
        - velocity
        - torque
        - led

    state_interfaces:
      joint_1:
        - position
        - velocity
        - torque
        - temperature
        - hardware_error
        - enabled
        - hw_fail_counter
        - last_time_read
        - firmware_version_major
        - firmware_version_minor
        - firmware_version_patch
      joint_2:
        - position
        - velocity
        - torque
        - temperature
        - hardware_error
        - enabled
        - hw_fail_counter
        - last_time_read
        - firmware_version_major
        - firmware_version_minor
        - firmware_version_patch
      joint_3:
        - position
        - velocity
        - torque
        - temperature
        - hardware_error
        - enabled
        - hw_fail_counter
        - last_time_read
        - firmware_version_major
        - firmware_version_minor
        - firmware_version_patch
      joint_4:
        - position
        - velocity
        - torque
        - temperature
        - voltage
        - hw_error
        - enabled
      joint_5:
        - position
        - velocity
        - torque
        - temperature
        - voltage
        - hw_error
        - enabled
      joint_6:
        - position
        - velocity
        - torque
        - temperature
        - voltage
        - hw_error
        - enabled
      tool:
        - position
        - velocity
        - torque
        - temperature
        - voltage
        - hw_error
        - enabled
