controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


niryo_one_controller:
  ros__parameters:
    type: niryo_one_hardware/NiryoOneController
    joints:
      - joint_1
      - joint_2
      - joint_3

    command_interfaces:
      - position
      - velocity
      - torque
      - mirco_steps
      - max_effort

    state_interfaces:
      - position
      - velocity
      - torque
      - temperature
      - hardware_error
      - enabled
