controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


niryo_one_controller:
  ros__parameters:
    type: niryo_one_hardware/NiryoOneController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    gpios:
      - hardware
    gpio_interfaces:
      - test_motors
      - calibrate_motors
      - request_new_calibration
      - activate_learning_mode
      - activate_leds
      - ping_and_set_dxl_tool
      - ping_and_set_conveyor
      - control_conveyor
      - update_id_conveyor
      - open_gripper
      - close_gripper
      - pull_air_vacuum_pump
      - push_air_vacuum_pump
      - change_hardware_version
      - send_custom_dxl_value
      - reboot_motors
