hardware_version: 2
use_sim: 'false'
stepper_1_home_position: 0.0
stepper_2_home_position: 0.64
stepper_3_home_position: -1.39
stepper_4_home_position: 0.0
can_enabled: 'true'
dxl_enabled: 'false'
niryo_one_hw_check_connection_frequency: 2.0
reboot: 'true'

spi_channel: 0
spi_baudrate: 1000000
gpio_can_interrupt: 25
can_hw_control_loop_frequency: 1500.0
can_hw_write_frequency: 50.0
can_hw_check_connection_frequency: 3.0
calibration_timeout: 40
required_steppers_ids: 1,2,3
allowed_steppers_ids: 1,2,3,6,7
gear_ratio_1: 6.0625
gear_ratio_2: 8.3125
gear_ratio_3: 7.875
gear_ratio_4: 5.0
gear_ratio_6: 5.0
gear_ratio_7: 5.0
home_position_1: 0.0
home_position_2: 0.640187
home_position_3: -1.397485
home_position_4: 0.0
offset_position_1: 3.05433
offset_position_2: 0.640187
offset_position_3: -1.397485
offset_position_4: 0.0
direction_1: -1.0
direction_2: -1.0
direction_3: 1.0
direction_4: -1.0
max_effort_1: 90
max_effort_2: 130
max_effort_3: 130
max_effort_4: 90
max_effort_6: 90
max_effort_7: 90

device_name: /dev/ttyAMA0
uart_baudrate: 1000000
dxl_hw_control_loop_frequency: 100.0
dxl_hw_write_frequency: 50.0
dxl_hw_data_read_frequency: 15.0
dxl_hw_status_read_frequency: 0.5
required_dxl_ids: 2,3,6
allowed_dxl_ids: 2,3,6,11,12,13,31
