planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  robot_description_semantic: "robot_description_semantic"
  robot_description_planning: "robot_description_planning"
  robot_description_kinematics: "robot_description_kinematics"
  publish_planning_scene: true
  publish_geometry_updates: true
  publish_state_updates: true
  publish_transforms_updates: true

trajectory_execution:
  execution_duration_monitoring: false
  allowed_start_tolerance: 0.0

start_state_max_bounds_error: 0.3
